# Workflow name
name: Backend Continuous Integration

# Triggers for the workflow
on:
  workflow_dispatch:
  
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'

# Jobs defined in the workflow
jobs:
  LINT-JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies Run
        run: |
          pipenv install --dev
          pipenv run lint
        working-directory: ./starter/backend

  TEST-JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies Run
        run: |
          pipenv install --dev
          pipenv run test
        working-directory: ./starter/backend

  BUILD-JOB:
    needs: [LINT-JOB, TEST-JOB]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kill existing process using port 5000
        run: |
          if lsof -i :5000; then
            sudo kill -9 $(lsof -t -i :5000)
          fi    

      - name: Build Docker image
        run: |
          docker build --tag mp-backend:latest .
          docker run -p 5000:5000 --name mp-backend -d mp-backend
        working-directory: ./starter/backend

      - name: Check Docker
        run:  |
          curl http://localhost:5000/movies
          docker logs -f mp-backend &
        working-directory: ./starter/backend
        
      - name: Stop Application
        run: |
          if [ "$(docker ps -q -f name=mp-backend)" ]; then
            docker stop mp-backend
            docker rm mp-backend
          fi
        working-directory: ./starter/backend