# Workflow name
name: backend-ci

# Triggers for the workflow
on:
  workflow_dispatch:
  
  push:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  LINT-JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' 

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies Run
        run: |
          pipenv install --dev
          pipenv run lint
        working-directory: ./starter/backend

  TEST-JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' 

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies Run
        run: |
          pipenv install --dev
          pipenv run test
        working-directory: ./starter/backend

  BUILD-JOB:
    needs: [LINT-JOB, TEST-JOB]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' 

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependenciesand Run
        run: |
          pipenv install --dev
          pipenv run serve &
        working-directory: ./starter/backend          

      - name: Build Docker image
        run: |
          docker build --tag mp-backend:latest .
          docker run -p 5000:5000 --name mp-backend -d mp-backend
        working-directory: ./starter/backend

      - name: Check Docker
        run:  |
          curl http://localhost:5000/movies
          docker logs -f mp-backend
        working-directory: ./starter/backend
        
      - name: Stop Application
        run: docker stop
        working-directory: ./starter/backend